"""initial schema — users, lifecycle_profiles, opportunities, analyses, contacts

Revision ID: 0001_initial
Revises:
Create Date: 2026-07-20

Handwritten (not autogenerated) so `alembic upgrade head` builds all 5 tables
deterministically without needing a live DB to diff against. Mirrors app/models.py.
"""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("cognito_sub", sa.String(length=255), nullable=True),
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index("ix_users_cognito_sub", "users", ["cognito_sub"], unique=True)

    op.create_table(
        "opportunities",
        sa.Column("id", sa.String(length=255), primary_key=True),
        sa.Column("title", sa.String(length=1000), nullable=False),
        sa.Column("agency", sa.String(length=500), nullable=False),
        sa.Column("naics", sa.String(length=20), nullable=True),
        sa.Column("set_aside", sa.String(length=255), nullable=True),
        sa.Column("response_deadline", sa.Date(), nullable=True),
        sa.Column("estimated_value", sa.Numeric(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "lifecycle_profiles",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("capabilities", sa.JSON(), nullable=True),
        sa.Column("target_agencies", sa.JSON(), nullable=True),
        sa.Column("naics_codes", sa.JSON(), nullable=True),
        sa.Column("past_performance", sa.JSON(), nullable=True),
        sa.Column("contract_vehicles", sa.JSON(), nullable=True),
        sa.Column("set_aside_status", sa.JSON(), nullable=True),
        sa.Column("size_min", sa.Numeric(), nullable=True),
        sa.Column("size_max", sa.Numeric(), nullable=True),
        sa.Column("source_s3_key", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index(
        "ix_lifecycle_profiles_user_id", "lifecycle_profiles", ["user_id"]
    )

    op.create_table(
        "analyses",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("opportunity_id", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("compatibility_score", sa.Float(), nullable=False),
        sa.Column("verdict", sa.String(length=20), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("factors", sa.JSON(), nullable=True),
        sa.Column("obligations", sa.JSON(), nullable=True),
        sa.Column("generated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
    )
    op.create_index("ix_analyses_opportunity_id", "analyses", ["opportunity_id"])
    op.create_index("ix_analyses_user_id", "analyses", ["user_id"])

    op.create_table(
        "contacts",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("opportunity_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("agency", sa.String(length=500), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("procurement_integrity_flag", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"], ["opportunities.id"], ondelete="CASCADE"
        ),
    )
    op.create_index("ix_contacts_opportunity_id", "contacts", ["opportunity_id"])


def downgrade() -> None:
    op.drop_table("contacts")
    op.drop_table("analyses")
    op.drop_table("lifecycle_profiles")
    op.drop_table("opportunities")
    op.drop_index("ix_users_cognito_sub", table_name="users")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
